// generated (10)/lib/components/ui/button.svelte
<script lang="ts">
  import { Loader2 } from 'lucide-svelte';
  
  let { 
    variant = 'primary', 
    size = 'md', 
    isLoading = false, 
    disabled = false, 
    class: className = '', 
    children, 
    ...props 
  } = $props();

  const baseStyles = "inline-flex items-center justify-center rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-background";
  
  const variants = {
    primary: "bg-blue-600 text-white hover:bg-blue-700 focus-visible:ring-blue-600",
    secondary: "bg-white text-gray-900 border border-gray-200 hover:bg-gray-100 focus-visible:ring-gray-400",
    ghost: "hover:bg-gray-100 text-gray-600 hover:text-gray-900",
    danger: "bg-red-600 text-white hover:bg-red-700 focus-visible:ring-red-600",
    outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground"
  };

  const sizes = {
    sm: "h-8 px-3 text-xs",
    md: "h-10 px-4 py-2",
    lg: "h-12 px-6 text-lg",
    icon: "h-10 w-10"
  };
</script>

<button
  class="{baseStyles} {variants[variant]} {sizes[size]} {className}"
  disabled={disabled || isLoading}
  {...props}
>
  {#if isLoading}
    <Loader2 class="mr-2 h-4 w-4 animate-spin" />
  {/if}
  {@render children?.()}
</button>

// generated (10)/components/Button.tsx
import React from 'react';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  isLoading?: boolean;
}

export const Button: React.FC<ButtonProps> = ({ 
  children, 
  variant = 'primary', 
  size = 'md', 
  isLoading = false,
  className = '',
  disabled,
  ...props 
}) => {
  const baseStyles = "inline-flex items-center justify-center rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none";
  
  const variants = {
    primary: "bg-blue-600 text-white hover:bg-blue-700 focus-visible:ring-blue-600",
    secondary: "bg-white text-gray-900 border border-gray-200 hover:bg-gray-100 focus-visible:ring-gray-400",
    ghost: "hover:bg-gray-100 text-gray-600 hover:text-gray-900",
    danger: "bg-red-600 text-white hover:bg-red-700 focus-visible:ring-red-600"
  };

  const sizes = {
    sm: "h-8 px-3 text-xs",
    md: "h-10 px-4 py-2",
    lg: "h-12 px-6 text-lg"
  };

  return (
    <button
      className={`${baseStyles} ${variants[variant]} ${sizes[size]} ${className}`}
      disabled={disabled || isLoading}
      {...props}
    >
      {isLoading && (
        <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
      )}
      {children}
    </button>
  );
};
